config/routes.rb
Asi::Application.routes.draw do
  resources :lists

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :gatunek, :nazwa, :pochodzenie, :rok

def self.search(nazwa)
if nazwa.present?
  find(:all, :conditions => ['Nazwa like ?', "%#{nazwa}%"])
  else
    scoped
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.json

def index

 if params[:nazwa]
    @lists = List.search(params[:nazwa])
  else
    @lists = List.all
  end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def create
  auth_hash = request.env['omniauth.auth']
  redirect_to "http://sigma.inf.ug.edu.pl:16444/lists"
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!-- <!DOCTYPE html>
<html>
<head>
  <title>Asi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>
-->
<!DOCTYPE html>
<html>
<head>
<!--<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Music website</title>
<meta name="description" content="Music website">
<meta name="keywords" content="music, mp3">
<link href="assets/stylesheets/application.css" rel="stylesheet" type="text/css">-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td height="1"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="1">
		<div style="position:absolute; top:6px; width:250px; margin-left:12px">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="1"><img src="http://sigma.ug.edu.pl/~dlewandowski/images/logo.gif" width="80" height="93"></td>
    <td class="c_name">Baza polskich zespolow rockowych</td>
  </tr>
</table>

		</div>
		<img src="http://sigma.ug.edu.pl/~dlewandowski/images/p1.jpg" width="660" height="112"></td>
        <td background="http://sigma.ug.edu.pl/~dlewandowski/images/pbg.gif" class="bgx">
		<div style="position:absolute; top:13px; width:190px; right:17px">
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
 <!-- <tr>
    <td width="120"><input name="textfield" type="text" class="login-form" value="search"></td>
    <td width="1"><a href="#"><input type="image" src="http://sigma.ug.edu.pl/~dlewandowski/images/btn-go.gif" alt="Go" width="34" height="22" border="0">
    </a></td>
  </tr> -->
</table>

		</div>
		<img src="http://sigma.ug.edu.pl/~dlewandowski/images/spacer.gif" width="1" height="1"></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td height="100%" valign="top"><table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td width="1" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><img src="http://sigma.ug.edu.pl/~dlewandowski/images/spacer.gif" width="192" height="1"></td>
          </tr>
          <tr>
            <td height="100%" class="l-text">Rock (ang. skała, kołysać się) – ogólna nazwa całego szeregu stylów muzycznych, wywodzących się z rock and rolla oraz rhythm and bluesa i bluesa. Sama nazwa "rock" jest właściwie skrótem od "rock and roll", choć można uznawać owe dwa pojęcia za odmienne od siebie gatunki muzyczne. Wszystkie style rockowe charakteryzują się brzmieniem opartym na różnego rodzaju gitarach (zwykle elektrycznych, elektrycznych basowych) i perkusji, z wyraźnie zarysowanym rytmem i śpiewem, wywodzącym się z bluesa, oraz sposobem wolnej improwizacji w trakcie grania utworów, wywodzącym się z jazzu.<br><i>wikipedia.pl</i></td>
          </tr>
        </table></td>
        <td width="1" height="100%" valign="top"><table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td><img src="http://sigma.ug.edu.pl/~dlewandowski/images/spacer.gif" alt="" width="1" height="1"></td>
          </tr>
          <tr>
            <td height="100%" bgcolor="#cae3f5"></td>
          </tr>
          <tr>
            <td height="1"><img src="http://sigma.ug.edu.pl/~dlewandowski/images/spacer.gif" width="1" height="6"></td>
          </tr>
        </table></td>
        <td valign="top"><table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td height="1" align="left" valign="top"><img src="http://sigma.ug.edu.pl/~dlewandowski/images/p2.jpg" width="441" height="69"></td>
          </tr>
          <tr>
            <td class="body_txt"><!--<h1>Zespoly muzyczne!</h1>-->
			<script type="text/javascript"><!--
google_ad_client = "pub-0500162490295296";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";
google_ad_type = "text";
//2006-11-21: Web templates - LAYOUTS
google_ad_channel = "0286771451";
google_color_border = "FFFFFF";
google_color_bg = "FFFFFF";
google_color_link = "0076BD";
google_color_text = "000000";
google_color_url = "B3B3B3";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

              <DIV style="border:#2570A4 solid 1px;padding:4px 6px 2px 6px"><%= yield %>
             </DIV>              <p>&nbsp;</p></td>
          </tr>
        </table></td>
      </tr>
    </table>
    <p>&nbsp;</p></td>
  </tr>
 </table>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nazwa %><br />
    <%= f.text_field :nazwa %>
  </div>
  <div class="field">
    <%= f.label :pochodzenie %><br />
    <%= f.text_field :pochodzenie %>
  </div>
  <div class="field">
    <%= f.label :gatunek %><br />
    <%= f.text_field :gatunek %>
  </div>
  <div class="field">
    <%= f.label :rok %><br />
    <%= f.number_field :rok %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Zespoły</h1>

<div class="szukajka"> 
	Wyszukaj zespół: <br />
	<%= form_tag lists_path, :method =>'get',id: "lists_search", class: "form-inline"  do %>
		<%= text_field_tag :nazwa, params[:nazwa] %>
		<%= submit_tag "Szukaj", :name => nil %>
	<% end %>
</div>

<table>
  <tr>
    <th>Nazwa</th>
    <th>Pochodzenie</th>
    <th>Gatunek</th>
    <th>Rok</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= list.nazwa %></td>
    <td><%= list.pochodzenie %></td>
    <td><%= list.gatunek %></td>
    <td><%= list.rok %></td>
    <td><%= link_to 'Show', list %></td>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nazwa:</b>
  <%= @list.nazwa %>
</p>

<p>
  <b>Pochodzenie:</b>
  <%= @list.pochodzenie %>
</p>

<p>
  <b>Gatunek:</b>
  <%= @list.gatunek %>
</p>

<p>
  <b>Rok:</b>
  <%= @list.rok %>
</p>


<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>